name: Build Linux autotracker

on: workflow_dispatch

jobs:
  build-autotracker-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
          upload_exe_with_name: 'magpie-autotracker-linux'
  build-autotracker-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
          upload_exe_with_name: 'magpie-autotracker'
