name: Build Linux autotracker

on: workflow_dispatch

jobs:
  build-autotracker-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
          upload_exe_with_name: 'magpie-autotracker'
